export const ACTIONS_GET_REQUEST = '@@action/ACTIONS_GET_REQUEST';
export const ACTIONS_GET_SUCCESS = '@@action/ACTIONS_GET_SUCCESS';
export const ACTIONS_GET_FAILURE = '@@action/ACTIONS_GET_FAILURE';

export const ACTIONS_POST_REQUEST = '@@action/ACTIONS_POST_REQUEST';
export const ACTIONS_POST_SUCCESS = '@@action/ACTIONS_POST_SUCCESS';
export const ACTIONS_POST_FAILURE = '@@action/ACTIONS_POST_FAILURE';
