export const MARK_POST_REQUEST = '@@mark/MARK_POST_REQUEST';
export const MARK_POST_SUCCESS = '@@mark/MARK_POST_SUCCESS';
export const MARK_POST_FAILURE = '@@mark/MARK_POST_FAILURE';

export const MARK_DELETE_REQUEST = '@@mark/MARK_DELETE_REQUEST';
export const MARK_DELETE_SUCCESS = '@@mark/MARK_DELETE_SUCCESS';
export const MARK_DELETE_FAILURE = '@@mark/MARK_DELETE_FAILURE';

export const MARK_PATCH_REQUEST = '@@mark/MARK_PATCH_REQUEST';
export const MARK_PATCH_SUCCESS = '@@mark/MARK_PATCH_SUCCESS';
export const MARK_PATCH_FAILURE = '@@mark/MARK_PATCH_FAILURE';