export const STUDENTS_GET_REQUEST = '@@student/STUDENTS_GET_REQUEST';
export const STUDENTS_GET_SUCCESS = '@@student/STUDENTS_GET_SUCCESS';
export const STUDENTS_GET_FAILURE = '@@student/STUDENTS_GET_FAILURE';

export const STUDENT_POST_REQUEST = '@@student/STUDENT_POST_REQUEST';
export const STUDENT_POST_SUCCESS = '@@student/STUDENT_POST_SUCCESS';
export const STUDENT_POST_FAILURE = '@@student/STUDENT_POST_FAILURE';

export const STUDENT_DELETE_REQUEST = '@@student/STUDENT_DELETE_REQUEST';
export const STUDENT_DELETE_SUCCESS = '@@student/STUDENT_DELETE_SUCCESS';
export const STUDENT_DELETE_FAILURE = '@@student/STUDENT_DELETE_FAILURE';

export const STUDENT_PATCH_REQUEST = '@@student/STUDENT_PATCH_REQUEST';
export const STUDENT_PATCH_SUCCESS = '@@student/STUDENT_PATCH_SUCCESS';
export const STUDENT_PATCH_FAILURE = '@@student/STUDENT_PATCH_FAILURE';