export const SUBJECT_POST_REQUEST = '@@subject/SUBJECT_POST_REQUEST';
export const SUBJECT_POST_SUCCESS = '@@subject/SUBJECT_POST_SUCCESS';
export const SUBJECT_POST_FAILURE = '@@subject/SUBJECT_POST_FAILURE';

export const SUBJECT_DELETE_REQUEST = '@@subject/SUBJECT_DELETE_REQUEST';
export const SUBJECT_DELETE_SUCCESS = '@@subject/SUBJECT_DELETE_SUCCESS';
export const SUBJECT_DELETE_FAILURE = '@@subject/SUBJECT_DELETE_FAILURE';

export const SUBJECT_PATCH_REQUEST = '@@subject/SUBJECT_PATCH_REQUEST';
export const SUBJECT_PATCH_SUCCESS = '@@subject/SUBJECT_PATCH_SUCCESS';
export const SUBJECT_PATCH_FAILURE = '@@subject/SUBJECT_PATCH_FAILURE';